name: Release
on:
  workflow_dispatch:
    inputs:
      release_type:
        description: Type of release
        type: choice
        required: true
        options:
          - patch
          - minor
          - major

env:
  VERSION-FILE-PATH: 'Sources/Example/Version.swift'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout main
        uses: actions/checkout@v3

      - name: Bump Version
        id: bump
        uses: ./.github/actions/bump-version
        with:
          version-file-path: ${{ env.VERSION-FILE-PATH }}
          release-type: ${{ inputs.release_type }}

      - name: Update Version File
        run: swift package --allow-writing-to-package-directory version-file --number ${{ steps.bump.outputs.version }}

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Update Version.swift
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          branch: example-patches
          delete-branch: true
          title: '[CI] Bump Version'
          body: |
            Update `Version.swift` with bumped version number
            - ${{ steps.bump.outputs.previous-version }} -> ${{ steps.bump.outputs.version }}
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          draft: false
